#!/usr/bin/env python3
"""
One-off: take the Google Fonts CSS already downloaded as google-fonts.css,
keep only the latin + latin-ext @font-face blocks, download the .woff2 files
into this directory, and write fonts.css with local url() paths.
"""
import re, os, urllib.request, pathlib

SRC = pathlib.Path("google-fonts.css").read_text()
KEEP_SUBSETS = {"latin", "latin-ext"}

# Each block is preceded by a /* <subset> */ comment, then @font-face { ... }
pattern = re.compile(r"/\*\s*([a-z0-9\-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", re.S)

kept_blocks, downloads, seen = [], [], {}
for m in pattern.finditer(SRC):
    subset, block = m.group(1), m.group(2)
    if subset not in KEEP_SUBSETS:
        continue
    woff = re.search(r"url\((https://fonts\.gstatic\.com[^)]+\.woff2)\)", block)
    if not woff:
        continue
    url = woff.group(1)
    fam_m = re.search(r"font-family:\s*'([^']+)'", block)
    weight_m = re.search(r"font-weight:\s*(\d+)", block)
    style_m = re.search(r"font-style:\s*(\w+)", block)
    fam = fam_m.group(1).replace(" ", "")
    weight = weight_m.group(1) if weight_m else "400"
    style = style_m.group(1) if style_m else "normal"
    if url in seen:
        local_name = seen[url]
    else:
        local_name = f"{fam}-{weight}{'i' if style == 'italic' else ''}-{subset}.woff2"
        seen[url] = local_name
        downloads.append((url, local_name))
    local_block = block.replace(url, f"./{local_name}")
    kept_blocks.append(f"/* {subset} */\n{local_block}")

for url, name in downloads:
    if not pathlib.Path(name).exists():
        print(f"  fetching {name}")
        urllib.request.urlretrieve(url, name)

out = "/* Self-hosted Google Fonts — generated by fonts/build-local-fonts.py */\n\n" + "\n\n".join(kept_blocks) + "\n"
pathlib.Path("fonts.css").write_text(out)
print(f"\nwrote fonts.css ({len(kept_blocks)} @font-face blocks, {len(downloads)} woff2 files)")
